version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: []
    command: /bin/bash -c
        "./wait-for.sh ${DB_HOST}:5432 &&
        ./manage.py collectstatic --noinput &&
        ./manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 conf.asgi:application"
#        gunicorn --bind 0.0.0.0:8000 conf.wsgi"

    volumes:
      - ./:/home/appuser/project/

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  worker:
    build: .
    entrypoint: ['celery']
    command: ['-A', 'conf', 'worker', '--loglevel=info']
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./:/home/appuser/project/

  beat:
    build: .
    entrypoint: ['celery']
    command: ['-A', 'conf', 'beat']
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./:/home/appuser/project/

  flower:
    build: .
    entrypoint: [ 'celery' ]
    command: [ '-A', 'conf', 'flower' ]
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./:/home/appuser/project/

  redis:
    image: redis:alpine

volumes:
  db-data:
