# Generated by Django 4.0 on 2021-12-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('students', models.ManyToManyField(related_name='courses_as_student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'Teacher'}, related_name='courses_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
