# Generated by Django 4.0 on 2021-12-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0003_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_answers', to='users.user')),
            ],
        ),
    ]
