# Generated by Django 3.2.12 on 2022-03-17 07:49

from django.db import migrations

def change_names(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    for course in Course.objects.all():
        course.name = 'Course number ' + str(course.pk)
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_mark_mark'),
    ]

    operations = [
        migrations.RunPython(change_names),
    ]
