# Generated by Django 3.2.12 on 2022-03-30 14:16

import courses.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220317_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='starts_at',
            field=models.DateField(default=datetime.date(2022, 3, 30), validators=[courses.validators.validate_date], verbose_name='Start date'),
        ),
    ]
